version: 0.0
os: linux

files:
  - source: ./
    destination: /tmp/warelypos-backend
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
